version: "3"

services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api:/backend/api
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"